In [26]:
import pandas as pd

# Create a dataset
# Let's build the values lists
value_n_list = ['Andrew', 'Phillip', 'John', 'Laura', 'Sophia', 'Michael', 'Emma', 'Daniel', 'Olivia', 'James', 'Liam', 'Isabella', 'Lucas']
value_w_list = [50, 78, 91.5, 60, 55.2, 85.4, 48.3, 74.1, 62.0, 80.5, 77.3, 50.0, 70.2]  # [kg]
value_h_list = [1.76, 1.87, 1.69, 1.65, 1.70, 1.80, 1.58, 1.75, 1.68, 1.85, 1.79, 1.60, 1.77]  # [m]
# value_bmi_list will be calculated: bmi = w/(h^2)
# value_bmi_list = [25]*13 # init values [kg/m2]

# Let's use a dictionary ({key:value})
# with the format {"str":list}
data_dict = {"Nombre": value_n_list,
             "Peso": value_w_list,
             "Altura": value_h_list  #,
             # "BMI": value_bmi_list
             }

print(data_dict)

# Turn a dictionary into a dataframe
df = pd.DataFrame(data_dict)
print(df)
df
# promt con DataFrame df: aadd another colum
df["bmi"] = df["Peso"] / (df["Altura"] ** 2)
print(df)
df
def calssifity_bmi(bmi):
    if bmi < 18.5:
        return "Peso insuficiente"
    elif 18.5 <= bmi < 24.9:
        return "peso normal"
    elif 25 <= bmi < 29.9:
        return "Sobrepeso"
    else:
        return "Obesidad"
df["bmi"] = df["bmi"].apply(calssifity_bmi)
print(df)
df
edad = [25, 30, 22, 28, 35, 40, 27, 33, 29, 31, 26, 24, 32]
df["Edad"] = edad
print(df)
df

{'Nombre': ['Andrew', 'Phillip', 'John', 'Laura', 'Sophia', 'Michael', 'Emma', 'Daniel', 'Olivia', 'James', 'Liam', 'Isabella', 'Lucas'], 'Peso': [50, 78, 91.5, 60, 55.2, 85.4, 48.3, 74.1, 62.0, 80.5, 77.3, 50.0, 70.2], 'Altura': [1.76, 1.87, 1.69, 1.65, 1.7, 1.8, 1.58, 1.75, 1.68, 1.85, 1.79, 1.6, 1.77]}
      Nombre  Peso  Altura
0     Andrew  50.0    1.76
1    Phillip  78.0    1.87
2       John  91.5    1.69
3      Laura  60.0    1.65
4     Sophia  55.2    1.70
5    Michael  85.4    1.80
6       Emma  48.3    1.58
7     Daniel  74.1    1.75
8     Olivia  62.0    1.68
9      James  80.5    1.85
10      Liam  77.3    1.79
11  Isabella  50.0    1.60
12     Lucas  70.2    1.77
      Nombre  Peso  Altura        bmi
0     Andrew  50.0    1.76  16.141529
1    Phillip  78.0    1.87  22.305471
2       John  91.5    1.69  32.036693
3      Laura  60.0    1.65  22.038567
4     Sophia  55.2    1.70  19.100346
5    Michael  85.4    1.80  26.358025
6       Emma  48.3    1.58  19.347861
7     Daniel  74.1    1.75  24.195918
8     Olivia  62.0    1.68  21.967120
9      James  80.5    1.85  23.520818
10      Liam  77.3    1.79  24.125339
11  Isabella  50.0    1.60  19.531250
12     Lucas  70.2    1.77  22.407354
      Nombre  Peso  Altura                bmi
0     Andrew  50.0    1.76  Peso insuficiente
1    Phillip  78.0    1.87        peso normal
2       John  91.5    1.69           Obesidad
3      Laura  60.0    1.65        peso normal
4     Sophia  55.2    1.70        peso normal
5    Michael  85.4    1.80          Sobrepeso
6       Emma  48.3    1.58        peso normal
7     Daniel  74.1    1.75        peso normal
8     Olivia  62.0    1.68        peso normal
9      James  80.5    1.85        peso normal
10      Liam  77.3    1.79        peso normal
11  Isabella  50.0    1.60        peso normal
12     Lucas  70.2    1.77        peso normal
      Nombre  Peso  Altura                bmi  Edad
0     Andrew  50.0    1.76  Peso insuficiente    25
1    Phillip  78.0    1.87        peso normal    30
2       John  91.5    1.69           Obesidad    22
3      Laura  60.0    1.65        peso normal    28
4     Sophia  55.2    1.70        peso normal    35
5    Michael  85.4    1.80          Sobrepeso    40
6       Emma  48.3    1.58        peso normal    27
7     Daniel  74.1    1.75        peso normal    33
8     Olivia  62.0    1.68        peso normal    29
9      James  80.5    1.85        peso normal    31
10      Liam  77.3    1.79        peso normal    26
11  Isabella  50.0    1.60        peso normal    24
12     Lucas  70.2    1.77        peso normal    32

      Nombre  Peso  Altura                bmi  Edad
0     Andrew  50.0    1.76  Peso insuficiente    25
1    Phillip  78.0    1.87        peso normal    30
2       John  91.5    1.69           Obesidad    22
3      Laura  60.0    1.65        peso normal    28
4     Sophia  55.2    1.70        peso normal    35
5    Michael  85.4    1.80          Sobrepeso    40
6       Emma  48.3    1.58        peso normal    27
7     Daniel  74.1    1.75        peso normal    33
8     Olivia  62.0    1.68        peso normal    29
9      James  80.5    1.85        peso normal    31
10      Liam  77.3    1.79        peso normal    26
11  Isabella  50.0    1.60        peso normal    24
12     Lucas  70.2    1.77        peso normal    32